Ejercicio 9: Matrices
Crea la siguiente matriz:

In [1]:
import numpy as np

In [2]:
matrix = np.array([
    [1, 4, 6, 5],
    [4, 1, 7, 3],
    [2, 9, 1, 2],
    [6, 3, 1, 1],
])

A todos los elementos de la matriz sumale un 10. Usando las funciones de numpy

In [6]:
np.add(matrix, 10)

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando las funciones de numpy

In [7]:
np.divide(np.add(matrix, 10), 2)

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])

A todos los elementos de la matriz sumale un 10. Usando operadores

In [8]:
matrix + 10

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

A todos los elementos de la matriz sumale un 10 y divídelos entre 2. Usando operadores

In [9]:
(matrix + 10) / 2

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])