In [2]:
import numpy as np

In [3]:
array_a = np.array([1, 2, 5, 7, 9, 12])
print(f"The 'array_a' is {array_a}")

The 'array_a' is [ 1  2  5  7  9 12]


In [4]:
array_b = array_a > 5
print(f"The 'array_b' (array_a > 5) is {array_b}")

The 'array_b' (array_a > 5) is [False False False  True  True  True]


In [5]:
array_a_prime = array_a[array_a > 5]
print(f"The 'array_a_prime' array_a[array_a > 5] is {array_a_prime}")

The 'array_a_prime' array_a[array_a > 5] is [ 7  9 12]


In [6]:
array_names = np.array(["Name1", "Name2", "Name3", "Name4", "Name5", "Name6"])
print(f"The 'array_names' of elements a > 5 is {array_names[array_a > 5]}")

The 'array_names' of elements a > 5 is ['Name4' 'Name5' 'Name6']


In [7]:
my_array = np.array([
    [10, 2, 9.5],
    [30, 7, 1.6],
    [60, 4, 8.2],
])
np.max(my_array, axis=0)

array([60. ,  7. ,  9.5])

In [8]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 1, 3],
    [9, -1, 3],
])
np.unique(my_array)

array([-1,  1,  2,  3,  4,  5,  6,  7,  9])

In [9]:
my_array = np.array([10, 20, 30, 40, 50], dtype=np.int8)
my_array.nbytes

5

In [10]:
my_array = np.array([10, 20, 30, 40, 50])
my_array.nbytes

20

In [11]:
np.set_printoptions(suppress=False)
a = np.array([0.000010, 0.000020, 0.000030, 0.000040, 0.000050])
print(a)

[1.e-05 2.e-05 3.e-05 4.e-05 5.e-05]


In [12]:
np.set_printoptions(suppress=True)
a = np.array([0.000010, 0.000020, 0.000030, 0.000040, 0.000050])
print(a)

[0.00001 0.00002 0.00003 0.00004 0.00005]


Casting arrays

In [13]:
my_array = np.array([[10, 20], [30, 40], [60, 70]])
print(my_array.nbytes)

my_array_casted = my_array.astype(np.uint8)
print(my_array_casted.nbytes)

24
6


In [14]:
my_array = np.array([[10, 20], [30, 40], [60, 70]])
print(my_array.nbytes)

my_array_casted = my_array.astype(np.float64)
print(my_array_casted.nbytes)

24
48


In [24]:
my_array = np.array([1.1, 2.2, 3.3])
print('Default:', my_array.dtype, '->', my_array.nbytes)

my_array_casted_64 = np.array([1.1, 2.2, 3.3])
print('Float64:', my_array_casted_64.dtype, '->', my_array_casted_64.nbytes)

my_array_casted_32 = my_array.astype(np.float32)
print('Float32:', my_array_casted_32.dtype, '->', my_array_casted_32.nbytes)

my_array_casted_16 = my_array.astype(np.float16)
print('Float16:', my_array_casted_16.dtype, '->', my_array_casted_16.nbytes)

Default: float64 -> 24
Float64: float64 -> 24
Float32: float32 -> 12
Float16: float16 -> 6
