Ejercicio 1
Crea una array de numpy con los siguiente números primos: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29



In [10]:
import numpy as np

In [11]:
primes = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

Muestra el último elemento. Y debes hacerlo sin saber su longitud.

In [12]:
primes[-1]

29

Muestra el 3º elemento

In [13]:
primes[2]

5

Muestra el último y 3º elemento.

In [17]:
primes[[-1, 2]]

array([29,  5])

Muestra del 2º al 5º elemento.

In [15]:
primes[1:5]

array([ 3,  5,  7, 11])

Muestra el 2° y el 5° elemento

In [16]:
primes[[1, 4]]

array([ 3, 11])

Muestra el último y el penúltimo elemento. Y debes hacerlo sin saber su longitud.

In [19]:
primes[[-1, -2]]

array([29, 23])