Ejercicio 3: Matrices
Crea la siguiente matriz:

In [10]:
import numpy as np
from tabulate import tabulate

In [11]:
matrix = np.array([
    [1, 4, 6, 5],
    [4, 1, 7, 3],
    [2, 9, 1, 2],
    [6, 3, 1, 1],
])

Muestra el elemento de la fila 2º y la columna 3º. Es el valor del 7.

In [12]:
matrix[1, 2]

7

Muestra la 3º Fila

In [13]:
matrix[2]

array([2, 9, 1, 2])

Muestra la 2º Columna

In [14]:
matrix[:, 1]

array([4, 1, 9, 3])

Muestra la 2º y 3º Columna

In [15]:
matrix[:, [1, 2]]

array([[4, 6],
       [1, 7],
       [9, 1],
       [3, 1]])

Muestra la 2º y 3º Fila

In [16]:
matrix[[1, 2], :]

array([[4, 1, 7, 3],
       [2, 9, 1, 2]])

Muestra la última columna. Debe funcionar independientemente del número de columnas.

In [17]:
matrix[:, -1]

array([5, 3, 2, 1])

Muestra la 2º y 4º Columna y la 1º y 3º fila

In [27]:
matrix[[0, 2]][:, [1, 3]]

array([[4, 5],
       [9, 2]])

Muestra de la 2º a la 3º Columna y de la 1º a la 3º fila

In [22]:
matrix[:3, 1:3]

array([[4, 6],
       [1, 7],
       [9, 1]])

Muestra todas las columnas excepto la primera y la última. Debe funcionar independientemente del número de columnas.

In [21]:
matrix[:, 1:-1]

array([[4, 6],
       [1, 7],
       [9, 1],
       [3, 1]])

Muestra todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas.

In [20]:
matrix[1:-1]

array([[4, 1, 7, 3],
       [2, 9, 1, 2]])

Muestra todas las columnas excepto la primera y la última y todas las filas excepto la primera y la última. Debe funcionar independientemente del número de filas y columnas.

In [19]:
matrix[1:-1, 1:-1]

array([[1, 7],
       [9, 1]])

Imprime la matriz y haz que las cabeceras de cada columna sean A, B , C y D

In [18]:
print(tabulate(matrix, headers=['A', 'B', 'C', 'D']))

  A    B    C    D
---  ---  ---  ---
  1    4    6    5
  4    1    7    3
  2    9    1    2
  6    3    1    1
