Ejercicio 9: Matrices
Crea la siguiente matriz:
[
    [1, 4, 6, 5],
    [4, 1, 7, 3],
    [2, 9, 1, 2],
    [6, 3, 1, 1]
]

In [6]:
import numpy as np

In [7]:
matrix = np.array([
    [1, 4, 6, 5],
    [4, 1, 7, 3],
    [2, 9, 1, 2],
    [6, 3, 1, 1]
])

A todos los elementos de la matriz súmale un 10. Usando las funciones de numpy

In [8]:
matrix_add10_function = np.add(matrix, 10)
matrix_add10_function

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

A todos los elementos de la matriz súmale un 10 y divídelos entre 2. Usando las funciones de numpy

In [9]:
matrix_add10_divide2_function = np.divide(np.add(matrix, 10), 2)
matrix_add10_divide2_function

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])

A todos los elementos de la matriz súmale un 10. Usando operadores

In [10]:
matrix_add10_operator = matrix + 10
matrix_add10_operator

array([[11, 14, 16, 15],
       [14, 11, 17, 13],
       [12, 19, 11, 12],
       [16, 13, 11, 11]])

A todos los elementos de la matriz súmale un 10 y divídelos entre 2. Usando operadores

In [11]:
matrix_add10_divide2_operator = (matrix + 10) / 2
matrix_add10_divide2_operator

array([[5.5, 7. , 8. , 7.5],
       [7. , 5.5, 8.5, 6.5],
       [6. , 9.5, 5.5, 6. ],
       [8. , 6.5, 5.5, 5.5]])