Ejercicio 4: Filtrado
El siguiente array contiene las temperaturas medias que ha hecho en Valencia en cada mes [10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8 ]


In [15]:
import numpy as np

In [16]:
temperatures = np.array([10.2, 10.7, 13.3, 15.8, 19.3, 23.6, 26, 25.9, 22.8, 19.1, 13.9, 10.8])

Muestra las temperaturas cuyo valor sea mayor que 20

In [17]:
temperatures[temperatures > 20]

array([23.6, 26. , 25.9, 22.8])

Muestra las temperaturas cuyo valor sea menor que 11

In [18]:
temperatures[temperatures < 11]

array([10.2, 10.7, 10.8])

Muestra las temperaturas cuyo valor sea mayor que 20 o menor que 11

In [22]:
temperatures[(temperatures > 20) | (temperatures < 11)]

array([10.2, 10.7, 23.6, 26. , 25.9, 22.8, 10.8])